### PR TITLE
Serghei3

### PR DESCRIPTION
**Pull request by vlaicu89**
New try

### CODE REVIEW

**Comment by AndreiDiAC** [comment]
nice :D

**Comment by wakshumA** [comment]
goog code

**Comment by wakshumA** [comment]
haha

**Review by wakshumA — APPROVED** [review]

**Review by tanya0509 — APPROVED** [review]

**Review by AndreiDiAC — APPROVED** [review]
This is a great salat :))

**Comment by vlaicu89** [comment]
come on, dont make fun of me)))

**Comment by wakshumA** [comment]
this group is amazing

**Review by wakshumA — CHANGES_REQUESTED** [review]
add more

**Pull request merged**
