### PR TITLE
completed the work

### PR DESCRIPTION
**Pull request by wakshumA**
added all

### CODE REVIEW

**Comment by AndreiDiAC** [comment]
good job ;D

**Review by AndreeaDruga — APPROVED** [review]
approved

**Review by tanya0509 — COMMENTED** [review]
lets see if I can aprove

**Comment by EkaterinaKuryleva** [comment]
I am here, can anybody see me

**Comment by EkaterinaKuryleva** [comment]
гыыыыыыыыыыыыы

**Comment by AndreeaDruga** [comment]
yes Kate, we can see you

**Pull request merged**
